CREATE TABLE dbo.SKU
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Code AS 's' + CAST(ID AS VARCHAR(10)) UNIQUE,
    Name NVARCHAR(255) NOT NULL
);
CREATE TABLE dbo.Family
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SurName NVARCHAR(255) NOT NULL,
    BudgetValue DECIMAL(18, 2) NOT NULL
);
CREATE TABLE dbo.Basket
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_SKU INT FOREIGN KEY REFERENCES dbo.SKU(ID),
    ID_Family INT FOREIGN KEY REFERENCES dbo.Family(ID),
    Quantity INT NOT NULL CHECK (Quantity >= 0),
    Value DECIMAL(18, 2) NOT NULL CHECK (Value >= 0),
    PurchaseDate DATETIME NOT NULL DEFAULT GETDATE(),
    DiscountValue DECIMAL(18, 2) NOT NULL
);
